server:
  port: 81

spring:
  redis:
    database: 11  #默认使用db0
    host: 192.168.1.44
    password: Sayyoo_redis_123
    port: 56679
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
#  datasource:
#    url: jdbc:oracle:thin:@192.168.10.215:1521/orclpdb
#    username: metadata
#    password: 123456
#    dbcp2:
#      driver: oracle.jdbc.driver.OracleDriver
#    other:
#      url: jdbc:mysql://192.168.10.240:3306/ibps109?characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
#      username: test
#      password: 123456
#      dbcp2:
#        driver: com.mysql.jdbc.Driver
  datasource:
    url: jdbc:mysql://192.168.1.44:56612/cjd?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: sayyoo
    password: sayyoo123
    dbcp2:
      driver: com.mysql.jdbc.Driver
    other:
      url: jdbc:mysql://192.168.1.44:56612/cjd?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: sayyoo
      password: sayyoo123
      dbcp2:
        driver: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
    hibernate.ddl-auto: none
  freemarker:
    cache: false
    suffix: .ftl
#     配置相对路径
#    template-loader-path: classpath:/ftl/
#     配置绝对路径
    template-loader-path: file:/Users/chengjiade/Desktop/simpleSpringBootProject/src/main/resources/ftl/hello.ftl
    charset: UTF-8

# REST超时配置
rest:
  ReadTimeout: 3000
  ConnectTimeout: 3000